services:
  db:
    container_name: auth-testing
    image: postgres
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "4020:5432"
  
volumes:
  data: